### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/statistics#1]
Build fails because `org.hamcrest:hamcrest-all:1.2` cannot be found.

[Maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.hamcrest%22%20AND%20a%3A%22hamcrest-all%22) indeed only has `1.1` and `1.3`.

**Comment by chrisdennis** [comment]
Merged PR, this should be fixed.
