### ISSUE TITLE
HitRatio not computed correctly

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/statistics#11]
The HitRatio should be obtained by dividing the HitCount by (HitCount+ MissCount), over a certain window of time; so that its value should be included between 0 and 1
Right now, it is just dividing the HitCount by MissCount, this is why we currently end up with values included between 0 and Infinity

**Comment by mathieucarbou** [comment]
@anthonydahanne we will still have "Infinite" displayed until there are some hits because if HitCount and MissCount are 0, then 0 / 0 is NaN

**Comment by anthonydahanne** [comment]
that's true, but that's expected and correct

**Comment by anthonydahanne** [comment]
It's a duplicate of https://github.com/ehcache/ehcache3/issues/1537 please follow progress there
