### ISSUE TITLE
Shadow tree association causes GC issues

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/statistics#13]
Usage in Ehcache of statistics has revealed that associations in the shadow tree can cause references to no longer be garbage collected. See ehcache/ehcache3#1328

Investigation should be performed to see if this situation can be resolved. And in the positive case how to resolve it.

**Comment by mathieucarbou** [comment]
```
Hi,

I think I found a slow memory leak in PassThroughStatistic.

Each PassThroughStatistic is added to the BINDING weak hash map. But that isn’t enough to have them recycled.

Running the following code will eventually go in OOME (use –Xmx40m to make it quicker).

A quick solution would be to clear them on cache manager close. But since stores and not closeable, I’m not sure how easy that is.

What do you think?

Thanks,
Henri

public class OffheapAllocation {

    @Test
    public void testPool() {

        for (int i = 0; i < 10_000; i++) {
            CacheManagerBuilder cacheManagerBuilder = newCacheManagerBuilder();
            CacheManager cacheManager = cacheManagerBuilder
                .withCache("cache", newCacheConfigurationBuilder(Long.class, byte[].class, newResourcePoolsBuilder()
                    .heap(1, EntryUnit.ENTRIES)))
                .build(true);

            Cache<Long, byte[]> cache = cacheManager.getCache("cache", Long.class, byte[].class);
            cache.put(1L, new byte[1000]);
            cacheManager.close();
        }
    }

}
```

I propose:

- we remove PassThroughStatistic.BINDING
- we remove PassThroughStatistic.bindStatistic()
- and we return PassThroughStatistic from StatisticsManager.createPassThroughStatistic() (2 methods)

then, all client code that calls StatisticsManager.createPassThroughStatistic() would need to keep a hard reference to PassThroughStatistic, until they do not use it.

This is what was already done for all other observers by the way. Passthrough is I think the only observer that works differently, but it wouldn’t be hard to make it work like the other observers.

tc-platform and ehcache are the only 2 projects that use PassThroughStatistic for now. The change is quite easy also for someone who knows how stats work.
